# Generated by Django 2.1.7 on 2019-03-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('place', models.SmallIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_profit_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Colors_pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('contains', models.ManyToManyField(to='paypixplaceapp.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('hex', models.CharField(max_length=9)),
                ('end_protection_date', models.DateField()),
                ('canvas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.Canvas')),
            ],
        ),
        migrations.CreateModel(
            name='Pixie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('pixie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.Pixie')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_num', models.IntegerField()),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.Color')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('pseudo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('pix', models.IntegerField()),
                ('max_ammo', models.IntegerField()),
                ('ammo', models.IntegerField()),
                ('last_ammo_usage', models.IntegerField()),
                ('ammo_reloading_seconds', models.IntegerField()),
                ('owns', models.ManyToManyField(to='paypixplaceapp.Color')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.Role')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.User'),
        ),
        migrations.AddField(
            model_name='pixel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.User'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.User'),
        ),
    ]
