# Generated by Django 2.1.7 on 2019-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ammo',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='ammo_reloading_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_ammo_usage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_ammo',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='pix',
            field=models.IntegerField(default=0),
        ),
    ]
