# Generated by Django 2.1.7 on 2019-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0003_auto_20190306_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pix',
            field=models.IntegerField(default=200),
        ),
    ]
