# Generated by Django 2.1.7 on 2019-03-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0006_auto_20190306_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='canvas_id',
            new_name='canvas',
        ),
        migrations.AlterField(
            model_name='pixel',
            name='end_protection_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
