# Generated by Django 2.1.7 on 2019-03-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0007_auto_20190307_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudo',
        ),
    ]
