# Generated by Django 2.1.7 on 2019-03-13 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0008_remove_user_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='height',
        ),
        migrations.AlterField(
            model_name='canvas',
            name='width',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)]),
        ),
    ]
