# Generated by Django 2.1.7 on 2019-03-14 15:06

from django.db import migrations

def create_pixies(apps, schema_editor):
    Pixie = apps.get_model('paypixplaceapp', 'Pixie')

    p1 = Pixie(title="Commoner", price=1, number=200, bonus=0)
    p1.save()
    p2 = Pixie(title="Merchant", price=2, number=400, bonus=50)
    p2.save()
    p3 = Pixie(title="Pixel Lord", price=5, number=1100, bonus=400)
    p3.save()
    p4 = Pixie(title="Pixel Legend", price=20, number=6000, bonus=2000)
    p4.save()

class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0010_auto_20190314_1348'),
    ]

    operations = [
        migrations.RunPython(create_pixies),
    ]
