# Generated by Django 2.1.7 on 2019-03-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0010_auto_20190314_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_ammo_usage',
            new_name='last_ammo_reload',
        ),
    ]
