# Generated by Django 2.1.7 on 2019-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0011_auto_20190314_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='end_protection_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_ammo_reload',
            field=models.DateTimeField(null=True),
        ),
    ]
