# Generated by Django 2.1.7 on 2019-03-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0012_auto_20190316_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_ammo_usage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paypixplaceapp.Role'),
        ),
    ]
