# Generated by Django 2.1.7 on 2019-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0013_auto_20190316_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='canvas',
            name='is_modified',
            field=models.BooleanField(default=True),
        ),
    ]
