# Generated by Django 2.1.7 on 2019-03-20 11:43

from django.db import migrations, models
import paypixplaceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0013_auto_20190316_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_type', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
