# Generated by Django 2.1.7 on 2019-03-20 11:44

from django.db import migrations

def create_pix_price(apps, schema_editor):
        PixPrice = apps.get_model('paypixplaceapp', 'PixPrice')

        p1 = PixPrice(num_type=0, name="Fix Color", price=75)
        p1.save()
        p2 = PixPrice(num_type=1, name="Color Pack", price=175)
        p2.save()
        p3 = PixPrice(num_type=2, name="Random Color", price=30)
        p3.save()
        p4 = PixPrice(num_type=3, name="Unlock Slot", price=160)
        p4.save()
        p5 = PixPrice(num_type=4, name="Canvas Color Pack", price=35)
        p5.save()

class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0014_pixprice'),
    ]

    operations = [
        migrations.RunPython(create_pix_price),
    ]
