# Generated by Django 2.1.7 on 2019-03-21 15:31

from django.db import migrations

def create_color_packs(apps, schema_editor):
        Color = apps.get_model('paypixplaceapp', 'Color')
        ColorPack = apps.get_model('paypixplaceapp', 'Colors_Pack')

        red = Color(hex="#FF0000")
        red.save()

        white = Color(hex="#FFFFFF")
        white.save()

        black = Color(hex="#000000")
        black.save()

        german = ColorPack.objects.create(name="German", price=175)
        german.contains.set([red, white, black])

        blue = Color(hex="#0000FF")
        blue.save()

        france = ColorPack.objects.create(name="France", price=175)
        france.contains.set([blue, white, red])
        

class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0015_auto_20190320_1244'),
    ]

    operations = [
        migrations.RunPython(create_color_packs),
    ]
