# Generated by Django 2.1.7 on 2019-03-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0016_auto_20190321_1631'),
        ('paypixplaceapp', '0014_auto_20190325_1440'),
    ]

    operations = [
    ]
