# Generated by Django 2.1.7 on 2019-03-27 14:42

from django.db import migrations

def create_pix_price(apps, schema_editor):
        PixPrice = apps.get_model('paypixplaceapp', 'PixPrice')

        p1 = PixPrice(num_type=5, name="Max Ammo", price=20)
        p1.save()
        
        p2 = PixPrice(num_type=6, name="Refill Time", price=40)
        p2.save()

        p3 = PixPrice(num_type=7, name="Instant Ammo", price=5)
        p3.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0019_auto_20190326_2134'),
    ]

    operations = [
        migrations.RunPython(create_pix_price),
    ]
