# Generated by Django 2.1.7 on 2019-03-27 15:41

from django.db import migrations

def create_pix_price(apps, schema_editor):
        PixPrice = apps.get_model('paypixplaceapp', 'PixPrice')

        p1 = PixPrice(num_type=8, name="Canvas Profit Creation", price=250)
        p1.save()
        
        p2 = PixPrice(num_type=9, name="Canvas Profit Activation", price=375)
        p2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0020_auto_20190327_1542'),
    ]

    operations = [
        migrations.RunPython(create_pix_price),
    ]
