# Generated by Django 2.1.7 on 2019-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0021_auto_20190327_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='end_protection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
