# Generated by Django 2.1.7 on 2019-03-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0023_auto_20190329_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={'ordering': ['-interactions']},
        ),
    ]
