# Generated by Django 2.1.7 on 2019-03-29 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0024_auto_20190329_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='theme',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='width',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)]),
        ),
    ]
