# Generated by Django 2.1.7 on 2019-03-30 11:37

from django.db import migrations

def create_color_packs(apps, schema_editor):
        Color = apps.get_model('paypixplaceapp', 'Color')
        ColorPack = apps.get_model('paypixplaceapp', 'Colors_Pack')

        white = Color.objects.get(hex="#000000")

        black = Color.objects.get(hex="#FFFFFF")

        grey = Color.objects.create(hex="#c5c5c5")

        color_blind = ColorPack.objects.create(name="Color Blind", price=175)
        color_blind.contains.set([white, grey, black])

        green_tea = Color.objects.create(hex="#a7ae3e")

        black_tea = Color.objects.create(hex="#660f15")

        oolong_tea = Color.objects.create(hex="#ba1801")

        tea = ColorPack.objects.create(name="Tea", price=175)
        tea.contains.set([green_tea, black_tea, oolong_tea])

        yellow = Color.objects.create(hex="#fcd238")

        orange_yellow = Color.objects.create(hex="#f5a800")

        orange = Color.objects.create(hex="#f18407")

        autumn = ColorPack.objects.create(name="Autumn", price=175)
        autumn.contains.set([yellow, orange_yellow, orange])

        light_blue = Color.objects.create(hex="#b7f2ff")

        lighter_blue = Color.objects.create(hex="#c4f8ff")

        blue = Color.objects.create(hex="#6bb1ff")

        winter = ColorPack.objects.create(name="Winter", price=175)
        winter.contains.set([light_blue, lighter_blue, blue])



class Migration(migrations.Migration):

    dependencies = [
        ('paypixplaceapp', '0025_auto_20190329_2038'),
    ]

    operations = [
        migrations.RunPython(create_color_packs),
    ]
